### ISSUE TITLE
Pion issues related to Galène

### ISSUE THREAD

**Issue by jech** [jech/galene#14]
- [ ] Slow ICE failures https://github.com/pion/ice/issues/271
- [ ] ICE Agent can not be restarted when gathering https://github.com/pion/ice/issues/280
- [ ] Issues with TCP ICE https://github.com/pion/webrtc/issues/1356 and https://github.com/pion/ice/issues/245
- [ ] Writes are where we spend most CPU time https://github.com/pion/ice/issues/128
- [ ] We're eating file descriptors for breakfast https://github.com/pion/ice/issues/76
- [ ] We're allocating encryption contexts like crazy https://github.com/pion/srtp/pull/76 and https://github.com/golang/go/issues/39365
- [ ] We're allocating too many buffers https://github.com/pion/srtp/pull/77
